# Change these first
owner: oskarbukovsky # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Hosting Panel
    url: https://panel.vagonbrei.eu/
  - name: Minecraft Server
    check: "tcp-ping"
    url: doranda.vagonbrei.eu
    port: 26567
    icon: https://raw.githubusercontent.com/oskarbukovsky/status/refs/heads/master/assets/server-icon.png
  - name: Plan
    url: https://plan.666777123.xyz/
  - name: Dynmap
    url: https://dynmap-tech-craft.666777123.xyz/

skipDeleteIssues: true 

status-website:
  name: ⚡| Tech-Craft™ |⚡ Status
  logoUrl: https://raw.githubusercontent.com/oskarbukovsky/status/refs/heads/master/assets/server-icon.png
  favicon: https://raw.githubusercontent.com/oskarbukovsky/status/refs/heads/master/assets/server-icon.png
  theme: night
  
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.666777123.xyz
  # baseUrl: /status
  introTitle: "**⚡| Tech-Craft™ |⚡ ** monitorovací stránka"
  introMessage: Jednoduchá status stránka využívající github actions
  # navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "59 0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: Naposledy aktualizováno v *$(date +'%H:%M:%S %d.%m.%Y')*
